import WatchImg from "../../assets/images/products/watch.png";
import HeadphonesImg from "../../assets/images/products/headphones.png";
import BackpackImg from "../../assets/images/products/backpack.png";
import ShoesImg from "../../assets/images/products/shoes.png";
import PerfumeImg from "../../assets/images/products/perfume.png";

export const productsData = [
  {
    id: 1,
    title: "Smart Watch Series 5",
    category: "Accessories",
    image: WatchImg,
    rating: 4.5,
    reviews: 120,
    price: 89.99,
    oldPrice: 129.99,
  },
  {
    id: 2,
    title: "Wireless Headphones",
    category: "Electronics",
    image: HeadphonesImg,
    rating: 4.7,
    reviews: 98,
    price: 59.99,
    oldPrice: 89.99,
  },
  {
    id: 3,
    title: "Travel Backpack",
    image: BackpackImg,
    rating: 4.6,
    reviews: 154,
    price: 39.99,
    oldPrice: 59.99,
  },
  {
    id: 4,
    title: "Running Shoes",
    category: "Sports",
    image: ShoesImg,
    rating: 4.4,
    reviews: 78,
    price: 49.99,
    oldPrice: 79.99,
  },
  {
    id: 5,
    title: "Luxury Perfume",
    category: "Beauty",
    image: PerfumeImg,
    rating: 4.8,
    reviews: 64,
    price: 29.99,
    oldPrice: 49.99,
  },
  {
    id: 6,
    title: "Smart Watch Series 5",
    category: "Accessories",
    image: WatchImg,
    rating: 4.5,
    reviews: 120,
    price: 89.99,
    oldPrice: 129.99,
  },
  {
    id: 7,
    title: "Wireless Headphones",
    category: "Electronics",
    image: HeadphonesImg,
    rating: 4.7,
    reviews: 98,
    price: 59.99,
    oldPrice: 89.99,
  },
  {
    id: 8,
    title: "Travel Backpack",
    image: BackpackImg,
    rating: 4.6,
    reviews: 154,
    price: 39.99,
    oldPrice: 59.99,
  },
  {
    id: 9,
    title: "Running Shoes",
    category: "Sports",
    image: ShoesImg,
    rating: 4.4,
    reviews: 78,
    price: 49.99,
    oldPrice: 79.99,
  },
  {
    id: 10,
    title: "Luxury Perfume",
    category: "Beauty",
    image: PerfumeImg,
    rating: 4.8,
    reviews: 64,
    price: 29.99,
    oldPrice: 49.99,
  },
  {
    id: 11,
    title: "Smart Watch Series 5",
    category: "Accessories",
    image: WatchImg,
    rating: 4.5,
    reviews: 120,
    price: 89.99,
    oldPrice: 129.99,
  },
  {
    id: 12,
    title: "Wireless Headphones",
    category: "Electronics",
    image: HeadphonesImg,
    rating: 4.7,
    reviews: 98,
    price: 59.99,
    oldPrice: 89.99,
  },
  {
    id: 13,
    title: "Travel Backpack",
    image: BackpackImg,
    rating: 4.6,
    reviews: 154,
    price: 39.99,
    oldPrice: 59.99,
  },
  {
    id: 14,
    title: "Running Shoes",
    category: "Sports",
    image: ShoesImg,
    rating: 4.4,
    reviews: 78,
    price: 49.99,
    oldPrice: 79.99,
  },
  {
    id: 15,
    title: "Luxury Perfume",
    category: "Beauty",
    image: PerfumeImg,
    rating: 4.8,
    reviews: 64,
    price: 29.99,
    oldPrice: 49.99,
  },
  {
    id: 16,
    title: "Smart Watch Series 5",
    category: "Accessories",
    image: WatchImg,
    rating: 4.5,
    reviews: 120,
    price: 89.99,
    oldPrice: 129.99,
  },
  {
    id: 17,
    title: "Wireless Headphones",
    category: "Electronics",
    image: HeadphonesImg,
    rating: 4.7,
    reviews: 98,
    price: 59.99,
    oldPrice: 89.99,
  },
  {
    id: 18,
    title: "Travel Backpack",
    image: BackpackImg,
    rating: 4.6,
    reviews: 154,
    price: 39.99,
    oldPrice: 59.99,
  },
  {
    id: 19,
    title: "Running Shoes",
    category: "Sports",
    image: ShoesImg,
    rating: 4.4,
    reviews: 78,
    price: 49.99,
    oldPrice: 79.99,
  },
  {
    id: 20  ,
    title: "Luxury Perfume",
    category: "Beauty",
    image: PerfumeImg,
    rating: 4.8,
    reviews: 64,
    price: 29.99,
    oldPrice: 49.99,
  },
];